### ISSUE TITLE
Weird Whitespace behavior when using custom RichTextRenderer

### ISSUE THREAD

**Issue by soerenmartius** [NordSecurity/storyblok-rich-text-astro-renderer#263]
Thanks for providing this awesome package. I just integrated it into one of my projects. I am facing a weird behavior: Whenever rendering custom components (e.g. `<Link/>`) as explained in your example, the resolver renders a whitespace which results in ugly formatting. Here's an example:

<img width="876" alt="Screenshot 2024-11-11 at 15 29 10" src="https://github.com/user-attachments/assets/69610156-99c9-4ec9-80a4-f440b712b5cd">

See the whitespace after `<Link>` component. Here's my custom `RichText` component:

```
---
import type { RichTextType } from 'storyblok-rich-text-astro-renderer'
import { storyblokEditable } from '@storyblok/astro'
import StoryblokComponent from '@storyblok/astro/StoryblokComponent.astro'
import RichTextRenderer from 'storyblok-rich-text-astro-renderer/RichTextRenderer.astro'
import BulletList from './BulletList.astro'
import CodeBlock from './CodeBlock.astro'
import InlineCode from './InlineCode.astro'
import Link from './Link.astro'
import Strong from './Strong.astro'
import Text from './Text.astro'

export interface Props {
  content: RichTextType
}

const { content } = Astro.props
---

<RichTextRenderer
  content={content}
  schema={{
    nodes: {
      heading: ({ attrs: { level } }) => ({
        component: Text,
        props: { variant: `h${level}` },
      }),
      // ordered_list: () => ({
      //   component: 'ol',
      //   props: {
      //     class: 'ordered-list',
      //   },
      // }),
      bullet_list: () => ({
        component: BulletList,
      }),
      code_block: ({ attrs }) => ({
        component: CodeBlock,
        props: { lang: attrs.class?.split('-')[1] },
      }),
    },
    marks: {
      code: () => ({
        component: InlineCode,
      }),
      bold: () => ({
        component: Strong,
      }),
      link: ({ attrs }) => {
        const { custom, ...restAttrs } = attrs

        return {
          component: Link,
          props: {
            link: { ...custom, ...restAttrs },
            class: '',
          },
        }
      },
    },
  }}
  resolver={(blok) => {
    return {
      component: StoryblokComponent,
      props: { blok },
    }
  }}
  {...storyblokEditable(content)}
/>
```

The link component looks like this:

```
---
import type { HTMLAttributes } from 'astro/types'
import type { Link } from 'storyblok-rich-text-astro-renderer'

export interface Props extends HTMLAttributes<'a'> {
  link: Link['attrs']
}

const {
  link: { href, target },
  ...props
} = Astro.props
---

<a {href} {target} {...props}><slot /></a>

<style>
  a {
    color: var(--info-foreground);
    text-decoration: none;
  }
  a:hover {
    text-decoration: underline;
  }
</style>
```

I also ensured that no whitespace is inserted using the editor (see the screenshot). 

<img width="881" alt="Screenshot 2024-11-11 at 15 29 35" src="https://github.com/user-attachments/assets/2c7aa6c4-c243-433a-a826-f8e1b6f07952">

I am using the custom `RichText` component in my components like this:

```
<RichText content={blok.subheadline} />
```

If I use the built-in `storyblok-rich-text-astro-renderer/RichTextRenderer.astro` component, it renders without the whitespace but obviously without my custom markup.

I would greatly appreciate any help!

**Comment by edvinasjurele** [comment]
Hi @soerenmartius, thank you for using this package 🙌 

I remember we had bumped into this issue already some time ago. This has to do with Astro, and not this package itself, especially when you use custom component, so it is so to say on the user side.

As I have checked in Astro project I have found https://github.com/withastro/astro/issues/6893 this working:

<img width="427" alt="image" src="https://github.com/user-attachments/assets/4881f05d-332d-42e5-8cc3-3167909e16b0" />

As I see you already do such thing already. I am also sure this may be dependant on Astro render engine, maybe they have patched it for good in some other versions, so you might doublecheck Astro version you use there.

I also see others trimming html when using rendering via slots.render https://github.com/overlayeddev/overlayed/commit/a43a8ae2cf5c3133381f4a942230793f468cc84b#diff-e0caaad24b7987567d35193c98990b0ede5bac280516907fe183be20611d805bR24 but it does not look as long-term solution either.

One more thing to think about is the order of HTML and Style tags. You might consider swaping them because I have gut feeling Astro renders empty white-space in this Astro component partial when rendering.

I checked and it seems it is indeed a culprit:

https://github.com/user-attachments/assets/b3be53b0-3e93-475a-b1d8-1d3e29f030f8

this example does not work ❌ 
```
<a {href} {target} {...props}><slot /></a>

<style>
  a { color: pink; }
</style>
```

while this works ✅ 
```
<style>
  a { color: pink; }
</style>

<a {href} {target} {...props}><slot /></a>
```

Let me know if that works for you.

**Comment by edvinasjurele** [comment]
![Screenshot 2024-12-30 at 09 47 09](https://github.com/user-attachments/assets/65548aaf-3d8d-4265-84fb-b5b0c3df53ba)

oh, I just realised that the issue persists in the projects code too - see `InlinedCode.astro` and `Styled.astro` components. This needs to be improved.
