### ISSUE TITLE
Astro v5 support

### ISSUE THREAD

**Issue by t-h-f** [NordSecurity/storyblok-rich-text-astro-renderer#282]
Seems like the dependencies won't resolve during `npm i` for an Astro 5 project using this package. Currently the peer dependency is set as `astro@"^3.0.0 || ^4.0.0"`.

**Comment by pdkn** [comment]
+1

**Comment by edvinasjurele** [comment]
Thanks guys for reporting this, I will check!

**Comment by edvinasjurele** [comment]
Hey guys, Astro v5 support should be part of https://github.com/NordSecurity/storyblok-rich-text-astro-renderer/releases/tag/v2.3.0 and is out now 🎉 

I did the peerDependency as `"astro": ">=3.x"` (instead of `"astro": "^3.0.0 || ^4.0.0 || ^5.0.0"`) so it states that package supported with all versions starting Astro v3, hence I see this as more future proof.

Check if that works for you now!
